### ISSUE TITLE
Why showing this error?

### ISSUE THREAD

**Issue by ridislam** [nahid/talk#1]
Where the problem you faced?

**Comment by ridislam** [comment]
Brother problem solved.

**Comment by Shipu** [comment]
how to solve you need to describe, not only for you for other users.... Use only **`Api list`** Method in `READ.md` file .

**Comment by nahid** [comment]
Where the problem you faced?

**Comment by ridislam** [comment]
that was solved brother, i have mistaken to understand one method how to use. but later i got that.thank you.

**Comment by nahid** [comment]
Test Issue

**Comment by nahid** [comment]
Comment from Ostad Class
