### ISSUE TITLE
Cannot install latest version with Laravel 5.5

### ISSUE THREAD

**Issue by dungnh** [nahid/talk#101]
On dev-master, the composer.json updated to support Laravel 5.5, but in latest released, it doesn't. 
Could you make a new release, please?

**Comment by ivanthecrazy** [comment]
+1

**Comment by harshadpathak** [comment]
+1

**Comment by ABwabsolute** [comment]
+1

**Comment by a1iraxa** [comment]
+1

**Comment by abdullahhafizh** [comment]
+1

**Comment by jake5253** [comment]
Add "nahid/talk": "dev-master" under 'require' in composer.json and then run composer update. Works fine.

**Comment by nahid** [comment]
#108

**Comment by nahid** [comment]
#108
