### ISSUE TITLE
PusherError

### ISSUE THREAD

**Issue by tobidsn** [nahid/talk#107]
In My Chrome console show error 
`Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4004,"message":"Account over quota"}}}`

how if you create a free realtime besides using the pusher?

**Comment by wmandai** [comment]
I think your pusher account temporarily reached its allowed quota.. 😄

**Comment by tobidsn** [comment]
Right, it looks like I have to buy a pro or not using a pusher
