### ISSUE TITLE
Talk Support for laravel 5.5.*

### ISSUE THREAD

**Issue by songokjesse** [nahid/talk#108]
can talk be installed on laravel 5.5 and above?
When i tried  composer require on laravel v5.5.34 this is what i get
Problem 1
    - Conclusion: remove laravel/framework v5.5.34
    - Conclusion: don't install laravel/framework v5.5.34
    - nahid/talk v2.2.0 requires illuminate/support 5.0.* || 5.1.* || 5.2.* || 5.3.* || 5.4.* ->
    - nahid/talk v2.2.1 requires illuminate/support 5.0.* || 5.1.* || 5.2.* || 5.3.* || 5.4.* ->

**Comment by wmandai** [comment]
For me i currently use the master. Add this line to your composer.json
`"nahid/talk": "dev-master",`

**Comment by nahid** [comment]
please use latest version
