### ISSUE TITLE
php artisan vendor:publish : Nothing to publish

### ISSUE THREAD

**Issue by visualight** [nahid/talk#110]
Hello,

I'm using Laravel : 5.2.45.
I installed Talk with command : composer require nahid/talk and I set the configuration in App => provides and aliases.

I get an error when I attempt to publish the package resources.

```
$ php artisan vendor:publish --provider="Nahid\Talk\TalkServiceProvider"
Nothing to publish for tag [].
```

What is wrong ?

**Comment by visualight** [comment]
Ok, sorry, I found the solution 👍 

`$ php artisan config:clear`

then

`$ php artisan vendor:publish --provider="Nahid\Talk\TalkServiceProvider"`

**Comment by nahid** [comment]
Which version of Laravel are you using?
