### ISSUE TITLE
How to detect if new message has come?

### ISSUE THREAD

**Issue by SerikK** [nahid/talk#112]
Hi. 
Good extension. But I have some problems.
I need to show to users that somebody recently received new message in my application. How I can do that?

**Comment by nahid** [comment]
Query with updated_at in conversations table

**Comment by SerikK** [comment]
Thanks for reply.
But how I can do in real time?

**Comment by nahid** [comment]
Why you need this?

**Comment by SerikK** [comment]
In general, our tech support answers to user questions. Users write to the chat. If user's waiting is too long, obviously they would leave our website. Or users chat with each other in order to communicate. They need fast messaging to do actions, deals and so on. We need so much that.

**Comment by SerikK** [comment]
Decided to implement like this https://pusher.com/tutorials/realtime-notifications

**Comment by nahid** [comment]
Talk is also Pusher ready with realtime chat. I think our doc will help you.

**Comment by SerikK** [comment]
I decided to integrate their notification solution into talk
