### ISSUE TITLE
SendMessageByUserID

### ISSUE THREAD

**Issue by sozonets** [nahid/talk#12]
sendMessageByUserId($userId, $message)

Hi, have a poser , when sending emails to the user (user_id), a letter comes constantly to himself .

**Comment by nahid** [comment]
please write details

**Comment by sozonets** [comment]
Talk::sendMessageByUserId('2','Hello');

http://prntscr.com/bj0snn

http://prntscr.com/bj0sty

**Comment by nahid** [comment]
do you set `Talk::setAuthUserId()` ?

**Comment by sozonets** [comment]
Yes

**Comment by nahid** [comment]
please share your code
