### ISSUE TITLE
Class talk does not exist!

### ISSUE THREAD

**Issue by Nazar0102** [nahid/talk#125]
Hi guys! After `composer update` I got this "Class talk does not exist"
I am trying `composer dump-autoload` but it still not working(

In `app/Http/Kernel.php` I have 

`'talk'       => \Nahid\Talk\Middleware\TalkMiddleware::class,`

In `config/app.php` in `providers` section 

`Nahid\Talk\TalkServiceProvider::class,`

and in `aliases` array

`'Talk'      => Nahid\Talk\Facades\Talk::class,`

What I did wrong? Any idea?

**Comment by Nazar0102** [comment]
oh, I see that problem is in the package version. It does't work with laravel"5.5.*"(((

**Comment by Nazar0102** [comment]
I'm using `"nahid/talk": "dev-master"`. And everything worked good until I updated composser. Even if I checkout or revert a lot of commits back I still have the same `"Class talk does not exist"`. If I use `Nahid\Talk\Talk` not `Nahid\Talk\Facades\Talk` all methods should not be called statically.

**Comment by Shohan494** [comment]
Same case, trying to downgrade laravel to 5.3 to have a further check.

**Comment by iamdatman** [comment]
Am having the same issue

ReflectionException in compiled.php line 1479:
Class talk does not exist

**Comment by Fidelite6** [comment]
**Same issue.**

**Comment by andresgcarmona** [comment]
I did a hotfix setting `return \Nahid\Talk\Talk::class;` instead of `return 'talk'`

<?php

namespace Nahid\Talk\Facades;

use Illuminate\Support\Facades\Facade;

class Talk extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return \Nahid\Talk\Talk::class;
    }
}

**Comment by andresgcarmona** [comment]
I did a hotfix setting return \Nahid\Talk\Talk::class; instead of return 'talk'

`<?php

namespace Nahid\Talk\Facades;

use Illuminate\Support\Facades\Facade;

class Talk extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return \Nahid\Talk\Talk::class;
    }
}`

**Comment by andresgcarmona** [comment]
I did a hotfix setting `return \Nahid\Talk\Talk::class; instead of `return 'talk'`

```
<?php

namespace Nahid\Talk\Facades;

use Illuminate\Support\Facades\Facade;

class Talk extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return \Nahid\Talk\Talk::class;
    }
}
```

**Comment by andresgcarmona** [comment]
I did a hotfix setting return `\Nahid\Talk\Talk::class;` instead of `return 'talk'`

```
<?php

namespace Nahid\Talk\Facades;

use Illuminate\Support\Facades\Facade;

class Talk extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return \Nahid\Talk\Talk::class;
    }
}
```

**Comment by Ravenna** [comment]
@andresgcarmona  that worked for me. Excited for a release that will solve the issue without a hotfix.

**Comment by nahid** [comment]
This problem was solved. Please use `v2.2.2` or `dev-master`
