### ISSUE TITLE
I want to implement this package but without using Pusher, is there a way out

### ISSUE THREAD

**Issue by malaymehta** [nahid/talk#126]
After reviewing the situation, I want to develop this without using Pusher. Is there any configuration that I can do to use this laravel echo server? 

Any guide or sample code will be helpful.

Thanks

**Comment by nahid** [comment]
Now Talk only ready for Pusher. If you want to using echo server, you have to develop your own implementation.

**Comment by malaymehta** [comment]
Ok, thanks for the response.
