### ISSUE TITLE
Facede Error

### ISSUE THREAD

**Issue by SadayNet** [nahid/talk#13]
Please update your service provider. New installations giving Facede Error. 
on line 72 `$this->app->alias('talk', Talk::class);` to `$this->app->alias('Talk', Talk::class);`
on line 82 `return ['talk'];` to `return ['Talk'];`

**Comment by nahid** [comment]
Thank you @SadayNet  for your report. I'll fix it asap

**Comment by SumonMSelim** [comment]
It's fixed. @nahid you may close it :)

**Comment by nahid** [comment]
Thank you @SumonMSelim vai :)
