### ISSUE TITLE
Laravel Websockets Integration

### ISSUE THREAD

**Issue by akkhan20** [nahid/talk#141]
Hello,
I tried integrating the package to use [Laravel-Websockets](https://github.com/beyondcode/laravel-websockets) which is drop in replacement for pusher but failed to get it running, I changed to pusher host on laravel side but in browser console i see it connecting to '<cluster>.pusher.com' instead of Websocket server that i have on local host.
Can you please guide me if it can be integrated with that package or not in current state so that we dont use pusher.com but use our own server.

**Comment by DimaBDV** [comment]
@akkhan20 #140 
If you want to use the web socket, you will have to abandon Pusher and use the "Laravel Echo Server + Socket.IO + Redis" bundle. (Here is the [link to the documentation](https://laravel.com/docs/5.7/broadcasting) )

**Comment by akkhan20** [comment]
yup thanks ill do it that way but i thought Laravel-websockets had some implementation for pusher client too anyway thanks for guiding
