### ISSUE TITLE
Looking forward to laravel 5.8 support

### ISSUE THREAD

**Issue by MoeCasts** [nahid/talk#142]
Looking forward to laravel 5.8 support

**Comment by badrul1329** [comment]
i'm also tried to use this package in laravel ver5.8.30 but found several error and not working, hence, looking forward for the update.
@nahid , are you available to make it updated?

**Comment by MoeCasts** [comment]
@badrul1329 I found a new package that can do the similar things. [https://github.com/musonza/chat](musonza/chat)

**Comment by nahid** [comment]
Updated: use version 2.30
