### ISSUE TITLE
how to make the talk app work for multiple models, like a customer chatting with a service provider,etc?

### ISSUE THREAD

**Issue by dmc4719** [nahid/talk#147]

**Comment by vaishnavmhetre** [comment]
I have a use-case where I need to create a chat for each lesson in a course and for the course altogether too! How do I accomplish it? Like any efficient way I could do this?

**Comment by nahid** [comment]
> I have a use-case where I need to create a chat for each lesson in a course and for the course altogether too! How do I accomplish it? Like any efficient way I could do this?

You may consider each lesson as an user, otherwise it won't be possible
