### ISSUE TITLE
how can i create a conversation?

### ISSUE THREAD

**Issue by 13dev** [nahid/talk#18]
how can i create a conversation?

**Comment by nahid** [comment]
just send a message using user id. 

```php
Talk::sendMessageByUserId($userId);
```

**Comment by 13dev** [comment]
ty ! what did not realize was that we passed parameter in this command?
if you put 0 or nothing return all inbox  if you pu the user id return empty array

**Comment by nahid** [comment]
You may first set authenticated users id like this

```php
Talk::setAuthUserId(auth()->user()->id);
```

and then call this method with a receiver id

```php
Talk::sendMessageByUserId($userId);
```

**Comment by 13dev** [comment]
sorry in this command `Talk::getInbox()` can you explain what is parameter's ?

**Comment by nahid** [comment]
Please read the doc. 
https://github.com/nahid/talk#getinbox

this method has two optional parameters `$offset` and `$take`

**Comment by 13dev** [comment]
and what they do, can you explain?
thanks in advance

**Comment by nahid** [comment]
Its helps to you to make pagination.
