### ISSUE TITLE
count unread messages

### ISSUE THREAD

**Issue by 13dev** [nahid/talk#19]
how i can count all unread messages of user ?

**Comment by nahid** [comment]
In inbox message are already count unread messages.

**Comment by newbielinuxuser** [comment]
@nahid which method should we use for count unread messages?

**Comment by 13dev** [comment]
getInbox

**Comment by newbielinuxuser** [comment]
@13dev 
Below is how I write the codes,

Controller
`$threads = Talk::threads(); return view('inbox', ['threads' => $threads]);`
View
`@foreach($threads as $value)
{{dd($value)}}
@endforeach`

Since threads are alias to getInbox, but even if i dump it, i still couldn't see the unread messages, what is the object name ?

**Comment by 13dev** [comment]
you have this?

Talk::setAuthUserId(auth()->user()->id);

**Comment by newbielinuxuser** [comment]
Yes, i put it as a constructor
    public function __construct() 
    {
        Talk::setAuthUserId(Auth::user()->id);
    }

**Comment by 13dev** [comment]
in controller dd($threads); before return and watch if returning anything

**Comment by 13dev** [comment]
and dd(Auth::user()->id);

**Comment by newbielinuxuser** [comment]
uh, yes, it does return something, same goes to the view that i commented just now, i just didn't know which object name it would be.

{#383 ▼
  +"thread": Message {#388 ▼
    #table: "messages"
    +timestamps: true
    #touches: array:1 [▶]
    +fillable: array:6 [▶]
    #connection: null
    #primaryKey: "id"
    #keyType: "int"
    #perPage: 15
    +incrementing: true
    #attributes: array:9 [▶]
    #original: array:9 [▶]
    #relations: array:1 [▶]
    #hidden: []
    #visible: []
    #appends: []
    #guarded: array:1 [▶]
    #dates: []
    #dateFormat: null
    #casts: []
    #observables: []
    #with: []
    #morphClass: null
    +exists: true
    +wasRecentlyCreated: false
  }
  +"withUser": User {#381 ▶}
}

**Comment by 13dev** [comment]
watch fillable

**Comment by newbielinuxuser** [comment]
+fillable: array:6 [▼
      0 => "message"
      1 => "is_seen"
      2 => "deleted_from_sender"
      3 => "deleted_from_receiver"
      4 => "user_id"
      5 => "conversation_id"
    ]

**Comment by 13dev** [comment]
is_seen return if message is read or not

**Comment by newbielinuxuser** [comment]
alright, so i have to loop and count manually ? since im trying to get the total unread message.

**Comment by 13dev** [comment]
you have to use getconversationByUserId() 
 add me on fb and i help you -> https://www.facebook.com/profile.php?id=100010762173757

**Comment by newbielinuxuser** [comment]
done
