### ISSUE TITLE
Non-static method Nahid\Talk\Talk::setAuthUserId() should not be called statically

### ISSUE THREAD

**Issue by thisismyaim** [nahid/talk#20]
I am following document and there is :

```
Talk::setAuthUserId(Auth::user()->id);
```

But getting error when use this

**Comment by nahid** [comment]
please install version 1.1.5 and try again :)

**Comment by sehsah** [comment]
where version 1.1.5 ? 
how can install it ?

**Comment by nahid** [comment]
@sehsah , to install version 1.1.5 just run this command in your terminal

```
composer require nahid/talk 1.1.5
```

**Comment by sehsah** [comment]
same error  !

**Comment by nahid** [comment]
please share your code and errors screenshot @sehsah
