### ISSUE TITLE
Routes, controllers and views

### ISSUE THREAD

**Issue by cmarfil** [nahid/talk#21]
As a suggestion, it would be great to have an example of controllers routes and views to integrate it in 10 minutes :D

**Comment by nahid** [comment]
Thank you @cmarfil for your helpful suggestion. Yes I'll do it as soon as possible

**Comment by kavin-90** [comment]
same here i want too Routes, controllers and views

**Comment by nahid** [comment]
Please check the master branch, I just working with it :)

**Comment by kavin-90** [comment]
Thanks for your hard work.

**Comment by RabiCodie** [comment]
Great work Nahid
Can you please give us a live exmaple Route Controllers & views to see how does it work :)
thanks

**Comment by nahid** [comment]
Yes, I just develop a example project for Talk. 

https://github.com/nahid/talk-example
