### ISSUE TITLE
Issue while deleting a message -- deleteMessage($messageId)

### ISSUE THREAD

**Issue by OdoricaAjency** [nahid/talk#22]
'deleted_from_reciever' is column name in database where as in the function its 'deleted_from_receiver'

**Comment by nahid** [comment]
ya, but it fixed in new version. Which version do you use?

**Comment by OdoricaAjency** [comment]
1.1.5
that's the latest version right??

**Comment by OdoricaAjency** [comment]
Talk.php line 280 $message->deleted_from_receiver = 1;
but in the db the column name is 'deleted_from_reciever'.

**Comment by nahid** [comment]
Thank you @OdoricaAjency for find it out. I just fixed it :)

**Comment by OdoricaAjency** [comment]
Hey this fix will not help.
Everywhere in the **code** it's 'deleted_from_reciever', changing the table column to 'deleted_from_receiver' will not help

All you need to do is change 'deleted_from_receiver' in Talk.php to 'deleted_from_reciever -- line 280

/nahid/talk/src/Conversations/ConversationRepository.php
/nahid/talk/src/Messages/Message.php
/nahid/talk/src/Messages/MessageRepository.php
all of the above files its 'deleted_from_reciever'.
