### ISSUE TITLE
'deleted_from_receiver' to be changed to 'deleted_from_reciever'  in Talk.php

### ISSUE THREAD

**Issue by OdoricaAjency** [nahid/talk#23]
Hey the latest fix will not help.
Everywhere in the code it's 'deleted_from_reciever', changing the table column to 'deleted_from_receiver' will not help

All you need to do is change 'deleted_from_receiver' in Talk.php to 'deleted_from_reciever -- line 280

/nahid/talk/src/Conversations/ConversationRepository.php
/nahid/talk/src/Messages/Message.php
/nahid/talk/src/Messages/MessageRepository.php
all of the above files its 'deleted_from_reciever'.

**Comment by nahid** [comment]
Please update then package with version 1.1.6 and manually rename your messages table field to `deleted_from_receiver`. I think it will work fine
