### ISSUE TITLE
  termimal show `Trying to get property of non-object`

### ISSUE THREAD

**Issue by nick198205** [nahid/talk#24]
After I installed talk using composer,added talk's service provider and alias into `app.php`,if I use `php artisan route:list` to list all my route,the terminal show errors to me :
```
  [ErrorException]                      
  Trying to get property of non-object
```

**Comment by nahid** [comment]
may be its not talk related errors. you may recheck your code.

**Comment by nick198205** [comment]
I have soveld this problem,with changing `Talk::setAuthUserId(auth()->user()->id);` to `if(auth()->user()){Talk::setAuthUserId(auth()->user()->id);}`.But now,a new problem comes to me,when I visit `http://localhost:8000/laravel-talk/example/message/inbox`,I saw 2 errors from console of my chrome:`jquery.min.js:2 Uncaught TypeError: Cannot read property 'classList' of null`,`jquery.min.js:2 Uncaught TypeError: $(...).getNiceScroll(...).doScrollTop is not a function`.

**Comment by nick198205** [comment]
I think all troubles I'm facing are because I haven't read your code line by line.I will read your example and document carefully again,thanks!
