### ISSUE TITLE
Talk::getInbox();

### ISSUE THREAD

**Issue by SpikeLV** [nahid/talk#25]
I try to use this function, but it returns only conversations where I'm a sender.
Is it right?

To get all conversation ( where I'm is as sender and where I'm is a replyer) which function do I need to use?

**Comment by nahid** [comment]
As a authenticated user sender and replyer is a same thing. So when you send a message its act as a sender or replyer

**Comment by SpikeLV** [comment]
I understand that, but by some reason I'm getting only where I'm sender

**Comment by nahid** [comment]
Please give me an example...

**Comment by SpikeLV** [comment]
Sent by mail

**Comment by samposin** [comment]
When i call Talk::getInbox() function after Talk::setAuthUserId(auth()->user()->id);
1. I am only getting one record.
2. One of the two login user, receiver id and sender id is same and also message is wrong
![issue](https://cloud.githubusercontent.com/assets/2486077/20628024/c634ead0-b349-11e6-86be-a9c0a78d09b2.png)
or
http://shareimage.posintechnologies.com/25_11_16_20_00_41.png

am i doing something wrong?

**Comment by nahid** [comment]
Yes you do something wrong, inbox mean messages thread. when you call `getInbox`, it return you all message tread where you involve. If you want to get all message with your desire user, you have to call `getConversationsById($conversationId)` or `getConversationsByUserId($userId)`.

@samposin

**Comment by samposin** [comment]
ok got it, thanks @nahid
