### ISSUE TITLE
Got error when run php artisan route:list command

### ISSUE THREAD

**Issue by fahribaharudin** [nahid/talk#26]
I got this error message when running php artisan route:list command:

PHP Fatal error:  Trait 'Illuminate\Foundation\Auth\Access\AuthorizesResources' not found in /home/fahri/Projects/thdc/project/vendor/nahid/talk/src/Example/TalkController.php on line 16

**Comment by nahid** [comment]
which version of Laravel you used?

**Comment by fahribaharudin** [comment]
Im using 5.3

**Comment by ptondereau** [comment]
@fahribaharudin for project >= 5.3.*, upgrade guides says:

>The AuthorizesResources trait has been merged with the AuthorizesRequests trait. You should remove the AuthorizesResources trait from your app/Http/Controllers/Controller.php file.

Remove it and it should work ;)

**Comment by fahribaharudin** [comment]
I already remove that trait from my base controller sir, It seems the error is on nahid/talk/src/Example/TalkController.php i noticed there is  AuthorizesResources trait too on that controller

**Comment by ptondereau** [comment]
@fahribaharudin this is because Example shouldn't be include when we get this package (same namespace) @nahid I advise you to move Example folder away from `src/` folder or add a line into .gitattributes to exclude it
