### ISSUE TITLE
Illegal offset type on doing php artisan route:list

### ISSUE THREAD

**Issue by rohit3nov** [nahid/talk#29]
on accessing **message/inbox** route after login and on doing **php artisan route:list,** showing Illegal offset type error :

ErrorException in Controller.php line 50:
**Illegal offset type**

I am using **laravel 5.1**
Nahid, could you help me ?
Thanks in advance.

**Comment by nahid** [comment]
This problem was solved

**Comment by nahid** [comment]
Duplicate #26
