### ISSUE TITLE
About Installation and Route List Error

### ISSUE THREAD

**Issue by tariqulislam** [nahid/talk#30]
I have Installed your project to laravel 5.1 and 5.3. After Installation I got error which is provided below
[Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Foundation\Auth\Access\AuthorizesResources' not found
Your package is not working yet.

**Comment by nahid** [comment]
please remove version 1.1.6 and try 1.1.7

**Comment by Jparrishau** [comment]
I am getting the same error. Using 1.1.7

**Comment by nahid** [comment]
Make sure its version 1.1.7. In this latest version there are no Example directory is available in package source. Please check it out.

**Comment by nahid** [comment]
This problem was solved

**Comment by nahid** [comment]
Duplicate #29
