### ISSUE TITLE
while migrating

### ISSUE THREAD

**Issue by 9818679544** [nahid/talk#34]
>php artisan migrate

                                                                          
  [Symfony\Component\Debug\Exception\FatalErrorException]                 
  Class 'Illuminate\Notifications\NotificationServiceProvider' not found

**Comment by azorpax** [comment]
what laravel version are you using?

**Comment by nahid** [comment]
Which laravel are you using @9818679544 ?

**Comment by cfpinto** [comment]
due to inactivity
