### ISSUE TITLE
Cant send a message

### ISSUE THREAD

**Issue by moritzwelsch** [nahid/talk#35]
I implemented your example sites and all works fine. 
I just simply cant send messages. Everytime i hit the "Send" button it gives back these 2 errors:
Uncaught TypeError: Cannot read property 'trim' of undefined(…)render @ index.js:30addMessage @ dispatch @ jquery.js:4430r.handle @ jquery.js:4116

POST http://localhost/ajax/message/send 500 (Internal Server Error)send @ jquery.js:8625ajax @ jquery.js:8161(anonymous function) @ talk.js:16dispatch @ jquery.js:4430r.handle @ jquery.js:4116
jquery.js:8625 XHR finished loading: POST "http://localhost/ajax/message/send".send @ jquery.js:8625ajax @ jquery.js:8161(anonymous function) @ talk.js:16dispatch @ jquery.js:4430r.handle @ jquery.js:4116

**Comment by nahid** [comment]
please remove index.js file from view. It will work fine

**Comment by sehsah** [comment]
Erro view chat 

Trying to get property of non-object (View: \resources\views\ajax\newMessageHtml.blade.php)

**Comment by moritzwelsch** [comment]
POST http://localhost:8000/ajax/message/send 500 (Internal Server Error)
send @ jquery.js:8625
ajax @ jquery.js:8161
(anonymous) @ talk.js:16
dispatch @ jquery.js:4430
r.handle @ jquery.js:4116

**Comment by nahid** [comment]
This issue should be in https://github.com/nahid/talk-example
