### ISSUE TITLE
Creating a new conversation

### ISSUE THREAD

**Issue by newbielinuxuser** [nahid/talk#36]
So how do we create a new conversation if the conversation doesn't exist ?

**Comment by nahid** [comment]
Just send a message `Talk::sendMessageByUserId($userId, $message)`. This system will automatically create a new conversation among this users.

**Comment by newbielinuxuser** [comment]
alright, thanks!
btw, what about the live chat? cuz i don't see it's running pusher after sending messages
I installed this via 'composer require nahid/talk' in my laravel 5.2 projects

**Comment by nahid** [comment]
I'll release it in next version. If you want to work with it you may run `composer install --prefer-source nahid/talk`
