### ISSUE TITLE
order conversations by latest message instead of latest conversation change?

### ISSUE THREAD

**Issue by haheute** [nahid/talk#38]
Would it be possible to order the conversations of a user by its latest created message?

When a message of a conversation is deleted, its conversation's `updated_at` seems to change and the conversation moves to top of the list, although it has no new message....

I think it would be nice if only the conversation with the latest/newest message would be on top of the list. No changes in the conversation list if a message is deleted.

**Comment by nahid** [comment]
Thank you for your kind information. I'll fixed it in next version
