### ISSUE TITLE
Pusher Support 

### ISSUE THREAD

**Issue by marwankhanfar** [nahid/talk#39]
Hello,
is pusher really working ? cause I checked the master and talk_live function is not called anywhere

**Comment by nahid** [comment]
Yes is working. Its used in `makeMessage()` method in `Talk.php`

**Comment by marwankhanfar** [comment]
I do see pusher events in my pusher account , however it's not reflected on interface , can you give me an example on how to embed  talk_live() js functionalites and where to provide it the $options variable it requires

**Comment by marwankhanfar** [comment]
nevermind , I figured it out . Thanks :+1:

**Comment by nahid** [comment]
You may follow http://github.com/nahid/talk-example
