### ISSUE TITLE
Composer is not installing latest version of talk package

### ISSUE THREAD

**Issue by marwankhanfar** [nahid/talk#40]
Package installed by composer does not match the version in the master

**Comment by nahid** [comment]
show any error?

**Comment by marwankhanfar** [comment]
no error , its downloading a version with no pusher support

**Comment by nahid** [comment]
ow, this version is not publish yet. you may use it from git clone

**Comment by marwankhanfar** [comment]
can you publish so we can pull it using composer ?

**Comment by nahid** [comment]
Talk v2.1.0 was released with realtime messaging. You may try. @marwankhanfar

**Comment by marwankhanfar** [comment]
Thanks alot :)
