### ISSUE TITLE
Frontend Layout

### ISSUE THREAD

**Issue by ghprod** [nahid/talk#5]
Hi, 

Could you share your frontend layout? its really clean :)

Thanks

**Comment by nahid** [comment]
Sure, its an open source project which is develop by my colleague @zafree . You can feel free to try it.
[BootAid Chat](http://zafree.github.io/bootaide/chat.html)

**Comment by zafree** [comment]
Thanks mate @nahid 

Hello @ghprod, fell free to use [bootaide](http://zafree.github.io/bootaide/). Hope you like it :)

**Comment by ghprod** [comment]
Thanks a lot @zafree  @nahid
