### ISSUE TITLE
Talk::setAuthUserId in Constructor doesn't work in Laravel 5.4

### ISSUE THREAD

**Issue by rishabgarg** [nahid/talk#54]
I'm using Laravel 5.4 and realized that Talk::setAuthUserId(Auth::user()->id), doesn't work in constructor anymore. I have to call Talk::setAuthUserId in all the methods (chatHistory, ajaxSendMessage, ajaxDeleteMessage) explicitly. 

Is there a fix for this in the latest version of Talk.

**Comment by akkhan20** [comment]
i have added this to my middleware for loggedin users.

**Comment by nahid** [comment]
From laravel 5.3 controller constructor execute before run middleware, so you can not access authenticated users info, check https://laracasts.com/discuss/channels/laravel/cant-call-authuser-on-controllers-constructor.

So solution is, you can make a middleware and write this code in `handle`section 

```php 
if (Auth::check()) {
            Talk::setAuthUserId(Auth::user()->id);
        }
        return $next($request);
```

and register this middleware in `Kernel.php` `middleware` array. I think this problem will solved.

Thank you
