### ISSUE TITLE
Session not working in your project

### ISSUE THREAD

**Issue by Pravinslk** [nahid/talk#57]
I have used your example project code and i saw you have used
```
protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Session\Middleware\StartSession::class,
    ];
```
so when we use this project other **session** not working our project if we comment this **startsession** getting error **trying to get non object** so what is the best way to use session with your example project code ?? [https://github.com/nahid/talk-example](this) 
 and if we install this our existing project we have to put `\Illuminate\Session\Middleware\StartSession::class,` line into **kernal** so i can't use session message .........

**Comment by nahid** [comment]
try v2.2.0
