### ISSUE TITLE
Facade not working

### ISSUE THREAD

**Issue by fishisawesome** [nahid/talk#6]
i followed the instructions in the Readme and got
`Call to undefined method Nahid\Talk\Facades\Talk::setAuthUserId()`

**Comment by nahid** [comment]
Sorry, its a minor bug. Thanks @fishisawesome for reporting it. Its already fixed. You may try _version :1.1.2_ or reinstall it.

**Comment by fishisawesome** [comment]
awesome, thanks

**Comment by hennessy7** [comment]
The problem still persists.

**Comment by nahid** [comment]
Try version 1.1.4

**Comment by hennessy7** [comment]
Same... 
FatalErrorException in Facade.php line 217: Call to undefined method Nahid\Talk\Facades\Talk::setAuthUserId()

**Comment by hennessy7** [comment]
How can I trick the facade?

**Comment by nahid** [comment]
in `TalkServiceProvider.php` change 
```php 
public function provides()
 {
        return ['Talk'];
 }
```
to 
```php 
public function provides()
 {
        return [Talk::class];
 }
```

**Comment by hennessy7** [comment]
Nothing changes. The function provides() is not being used.

**Comment by blueapple25** [comment]
Call to undefined method Nahid\EnvatoPHP\Facades\Envato::getAuthUrl()

**Comment by blueapple25** [comment]
Its my code in my controller

public function EnvatoData()
    {        
        $config = [
            "client_id"     => '',
        
            'client_secret' => '',
        
            "redirect_uri"  =>  '',
            
            'use_personal_token' => FALSE,

            'personal_token' => '',
            
            'app_name'      => '',
        ];        
        
        $envato = new Envato($config);
        $envato->getAuthUrl();
        
        $user = Envato::me()->accounts();
        dd($user->data);  
        
        return view('envato_signin');
    }

**Comment by blueapple25** [comment]
Note: - app credential i will not include in issue but set in my local file
