### ISSUE TITLE
Cant setAuthUserId in Laravel 5.4

### ISSUE THREAD

**Issue by packytagliaferro** [nahid/talk#61]
So I set up my MessageController.php like so:

```
<?php

namespace App\Http\Controllers;

use Auth;
use Illuminate\Http\Request;
use Nahid\Talk\Facades\Talk;

class MessageController extends Controller
{

    public function __construct()
    {
        Talk::setAuthUserId( Auth::id() );
    }

    public function index()
    {
      $inboxes = Talk::getInbox();

      return $inboxes;
    }
}
```

If I try and `dd( Talk::setAuthUserId( Auth::user() ) )` it returns `false` so the user is not being set. But if I hardcode an id in my construct like:

```
 public function __construct()
    {
        Talk::setAuthUserId( 2 );
    }

```
The user is set and I can get `$inboxes = Talk::getInbox();`

I know `Auth::id()` will return my user id of 2 so not sure what is going on

**Comment by zigstum** [comment]
Raised here also:
https://github.com/nahid/talk/issues/54

```
   public function __construct()
    {        
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            $id = Auth::user()->id;
            Talk::setAuthUserId($id);
            return $next($request);
        });
```
This seems to have worked for me (MessageController), found it on laracasts somewhere I think.

**Comment by nahid** [comment]
see the update documentation. You have to register `Talk` middleware and call it from controller constructor

```php
function __constructor()
{
    $this->middleware('talk');
}
```
