### ISSUE TITLE
pusher error "Path not found"

### ISSUE THREAD

**Issue by packytagliaferro** [nahid/talk#68]
I get this error from this code:

```
<script>
    var msgshow = function(data) {
        // write what you want with this data

        console.log(data);
    }
</script>

{!! talk_live(['user'=>["id"=>auth()->user()->id, 'callback'=>['msgshow']]]) !!}
```

talk.php config
```
'user' => [
        'model' => 'App\User',
    ],
    'broadcast' => [
        'enable' => true,
        'app_name' => env('APP_NAME', 'Punishment Leage'),
        'pusher' => [
            'app_key' => env('PUSHER_APP_KEY'),
            'app_secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
              'cluster' => env('PUSHER_APP_CLUSTER'),
              'encrypted' => true
            ],
        ],
    ],

```

env

```
PUSHER_APP_ID=XXXXX
PUSHER_APP_KEY=XXXXXXX
PUSHER_APP_SECRET=XXXXXXXX
PUSHER_APP_CLUSTER=us2
```

I tested with Pushers script so I know the env information is correct.

**Comment by nahid** [comment]
Please share your complete error meaagse

**Comment by nahid** [comment]
do you using Firefox?

**Comment by packytagliaferro** [comment]
Nope, I am using Chrome. 

Side note, I tried the JS from Pusher's site and it worked so not sure whats wrong.


JS from Pusher:

```
<script src="https://js.pusher.com/4.0/pusher.min.js"></script>
  <script>

    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    var pusher = new Pusher('XXXXXXXXXXXXX', {
      cluster: 'us2',
      encrypted: true
    });

    var channel = pusher.subscribe('my-channel');
    channel.bind('my-event', function(data) {
      alert(data.message);
    });
  </script>
```

**Comment by packytagliaferro** [comment]
Any news on this? Do I have to uncomment out the boilerplate Pusher stuff in the bootstrap.js file that comes with Laravel?

**Comment by nahid** [comment]
Did you set Cluster properly? Is your App key valid for this cluster?

**Comment by packytagliaferro** [comment]
@nahid Yep. I set the Cluster and the key as suggested in the talk.php config file:

```
'user' => [
        'model' => 'App\User',
    ],
    'broadcast' => [
        'enable' => true,
        'app_name' => env('APP_NAME', 'Punishment Leage'),
        'pusher' => [
            'app_key' => env('PUSHER_APP_KEY'),
            'app_secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
              'cluster' => env('PUSHER_APP_CLUSTER'),
              'encrypted' => true
            ],
        ],
    ],

```

Then in my ENV file I put the credidtials:

```
PUSHER_APP_ID=IIIIIIIIIIIII
PUSHER_APP_KEY=KKKKKKKKKKKK
PUSHER_APP_SECRET=SSSSSSSSSSSSSS
PUSHER_APP_CLUSTER=us2
```

I got these from Pusher.com:

```
app_id = "IIIIIIIIIIIII"
key = "KKKKKKKKKKKKKKK"
secret = "SSSSSSSSSSSS"
cluster = "us2"
```

**Comment by nahid** [comment]
please view source code from browser and take a screenshot where Talk automatically generate pusher code and send me it.

**Comment by packytagliaferro** [comment]
@nahid just emailed you. The error looks like its coming from pusherjs.blade.php line 8. You never add the Cluster and get the variable from the config file. When I hardcoded it in there to test it worked. 

Also note ( I can create a new issue). If you app name has a space in it (like MY App) you will get another error since a channel name cannot have spaces. You should add a function to replace any spaces in `$talk__appName` with `-`

**Comment by nahid** [comment]
Please update it to v2.2.1

**Comment by packytagliaferro** [comment]
@nahid Perfect. That update must have come out right after my initial install a month or so ago. All fixed.

**Comment by Paresh7622** [comment]
what is the solution @nahid @packytagliaferro
