### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by kernelpro** [nahid/talk#90]
![image](https://user-images.githubusercontent.com/14651257/32021756-feb3945c-b9dc-11e7-9072-b4d98da6017e.png)
Hi man, fix this error pls. my version illuminate/contracts is 5.5.19

Ty.

**Comment by x1mdev** [comment]
Same problem here

**Comment by kernelpro** [comment]
@x1mdev where?

**Comment by x1mdev** [comment]
I fixed it by using composer require nahid/talk dev-master

**Comment by x1mdev** [comment]
The composer package without dev-master does not work with laravel 5.5

**Comment by kernelpro** [comment]
@x1mdev its work, ty bro
