### ISSUE TITLE
Error viewing/showing messages from soft-deleted users

### ISSUE THREAD

**Issue by tviles** [nahid/talk#91]
The User relationship in the Messages model needs to have ->withTrashed() to allow messages to be viewed even if the user has been soft-deleted. Otherwise it throws an error. 

**Before:** 
public function user()
    {
        return $this->belongsTo(config('talk.user.model', 'App\User'));
    }

**After:** 
public function user()
    {
        return $this->belongsTo(config('talk.user.model', 'App\User'))->withTrashed();
    }

**Comment by nemiq** [comment]
Hi,
This change is now in dev-version, which breaks functionality for projects which do not use soft delete on user model. Add work around for those cases? Config?
